spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=blog;encrypt=true;trustServerCertificate=true
    username: cos
    password: cos1234
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update